import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/component/shared/header/navbar/Navbar";

export const metadata: Metadata = {
  title: "bdedujobs.info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <Navbar />
        <main className="container mx-auto pt-24 ">{children}</main>
      </body>
    </html>
  );
}
